# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title timesTwo
#' @description A Gibbs sampler using Rcpp
#' @param x the number of between-sample random numbers
#' @return a random sample of size a
#' @examples
#' \dontrun{
#' timesTwo(x)
#' }
#' @export
timesTwo <- function(x) {
    .Call('_StatComp20042_timesTwo', PACKAGE = 'StatComp20042', x)
}

