# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title perceptronC
#' @description  divide linearly separable datasets into two categories
#' @param w wight vector
#' @param b bias
#' @param l_rate learning rate
#' @param feature characteristic matrix
#' @param target category
#' @return  parameters of hyperplane
#' @examples
#' \dontrun{
#' data(iris_trim)
#' w = c(0,0)
#' b=0
#' f = iris_trim[,c(1,2)]
#' t = iris_trim[,5]
#' l_rate =0.001
#' perceptronC(w,b,l_rate,f,t)
#' }
#' @export
perceptronC <- function(w, b, l_rate, feature, target) {
    .Call('_StatComp20042_perceptronC', PACKAGE = 'StatComp20042', w, b, l_rate, feature, target)
}

